export interface Business {
  id: string;
  name: string;
  category: BusinessCategory;
  logo?: string;
  coverImage?: string;
  gallery?: string[];
  description: string;
  services: string[];
  address: string;
  phone: string;
  whatsapp?: string;
  email: string;
  website?: string;
  licenseNo?: string;
  rating: number;
  reviewCount: number;
  isVerified: boolean;
  isScamReported: boolean;
  importedFromGoogle: boolean;
  coordinates: {
    lat: number;
    lng: number;
  };
  openingHours?: {
    [key: string]: string;
  };
  reviews: Review[];
}

export interface Review {
  id: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  rating: number;
  comment: string;
  images?: string[];
  isVerified: boolean;
  date: string;
  businessResponse?: string;
}

export type BusinessCategory =
  | "Visa Agent"
  | "Visa Services"
  | "Visa & Passport Services"
  | "Immigration Consultants"
  | "Document Clearing / Typing Centers"
  | "Travel Agencies (Visa-related)";

export const businessCategories: BusinessCategory[] = [
  "Visa Agent",
  "Visa Services",
  "Visa & Passport Services",
  "Immigration Consultants",
  "Document Clearing / Typing Centers",
  "Travel Agencies (Visa-related)",
];

export const sampleBusinesses: Business[] = [
  {
    id: "1",
    name: "Dubai Visa Express",
    category: "Visa Services",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    gallery: ["/api/placeholder/300/200", "/api/placeholder/300/200"],
    description:
      "Leading visa service provider in Dubai with over 15 years of experience. We specialize in tourist, business, and residence visas for all nationalities.",
    services: [
      "Tourist Visa",
      "Business Visa",
      "Residence Visa",
      "Visa Renewal",
      "Emergency Visa",
    ],
    address: "Office 1205, Al Manara Tower, Business Bay, Dubai, UAE",
    phone: "+971-4-123-4567",
    whatsapp: "+971-50-123-4567",
    email: "info@dubaivisaexpress.com",
    website: "https://dubaivisaexpress.com",
    licenseNo: "DED-12345",
    rating: 4.8,
    reviewCount: 156,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: false,
    coordinates: { lat: 25.1887, lng: 55.2673 },
    openingHours: {
      Monday: "9:00 AM - 6:00 PM",
      Tuesday: "9:00 AM - 6:00 PM",
      Wednesday: "9:00 AM - 6:00 PM",
      Thursday: "9:00 AM - 6:00 PM",
      Friday: "9:00 AM - 6:00 PM",
      Saturday: "10:00 AM - 4:00 PM",
      Sunday: "Closed",
    },
    reviews: [
      {
        id: "r1",
        userId: "u1",
        userName: "Ahmed Hassan",
        userAvatar: "/api/placeholder/40/40",
        rating: 5,
        comment:
          "Excellent service! Got my family visa processed in just 3 days. Highly professional team.",
        isVerified: true,
        date: "2024-01-15",
        businessResponse:
          "Thank you Ahmed! We're delighted to have helped your family.",
      },
    ],
  },
  {
    id: "2",
    name: "Emirates Immigration Consultants",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "Certified immigration consultants specializing in UAE residence visas, golden visas, and citizenship services.",
    services: [
      "Golden Visa",
      "Investor Visa",
      "Skilled Worker Visa",
      "Family Reunion",
      "Citizenship Services",
    ],
    address: "Suite 2010, Emirates Towers, Sheikh Zayed Road, Dubai, UAE",
    phone: "+971-4-987-6543",
    whatsapp: "+971-50-987-6543",
    email: "contact@emiratesimmigration.ae",
    website: "https://emiratesimmigration.ae",
    licenseNo: "DED-67890",
    rating: 4.9,
    reviewCount: 203,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2183, lng: 55.2671 },
    reviews: [
      {
        id: "r2",
        userId: "u2",
        userName: "Sarah Johnson",
        rating: 5,
        comment:
          "Professional service for my golden visa application. The team was very knowledgeable and helpful throughout the process.",
        isVerified: true,
        date: "2024-01-10",
      },
    ],
  },
  {
    id: "3",
    name: "Al Manama Visa Center",
    category: "Visa Agent",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "Trusted visa agent providing comprehensive visa services for UAE visitors and residents since 2008.",
    services: [
      "Tourist Visa",
      "Visit Visa",
      "Business Visa",
      "Transit Visa",
      "Visa Cancellation",
    ],
    address:
      "Office 302, Al Attar Business Tower, Sheikh Zayed Road, Dubai, UAE",
    phone: "+971-4-321-7654",
    whatsapp: "+971-55-321-7654",
    email: "info@almanamavisa.com",
    website: "https://almanamavisa.com",
    licenseNo: "DED-33445",
    rating: 4.6,
    reviewCount: 189,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2048, lng: 55.2708 },
    reviews: [
      {
        id: "r3",
        userId: "u3",
        userName: "Michael Rodriguez",
        rating: 5,
        comment:
          "Amazing experience! They handled my urgent visa application perfectly. Received approval within 24 hours.",
        isVerified: true,
        date: "2024-01-18",
      },
      {
        id: "r4",
        userId: "u4",
        userName: "Fatima Al Zahra",
        rating: 4,
        comment:
          "Good service overall. Staff was helpful and process was smooth. Would recommend.",
        isVerified: false,
        date: "2024-01-12",
      },
    ],
  },
  {
    id: "4",
    name: "Gulf Immigration Services",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    description:
      "Expert immigration consultants offering specialized services for UAE residency, work permits, and family sponsorship.",
    services: [
      "Residence Visa",
      "Work Permit",
      "Family Sponsorship",
      "Visa Renewal",
      "Status Change",
    ],
    address: "Level 15, Burj Al Salam, Sheikh Zayed Road, Dubai, UAE",
    phone: "+971-4-445-8899",
    whatsapp: "+971-50-445-8899",
    email: "contact@gulfimmigration.ae",
    website: "https://gulfimmigration.ae",
    licenseNo: "DED-78901",
    rating: 4.7,
    reviewCount: 267,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2084, lng: 55.2719 },
    reviews: [
      {
        id: "r5",
        userId: "u5",
        userName: "Robert Smith",
        rating: 5,
        comment:
          "Outstanding service! They made my immigration process so easy. Highly professional team with excellent knowledge.",
        isVerified: true,
        date: "2024-01-20",
        businessResponse:
          "Thank you Robert! We're committed to making immigration stress-free.",
      },
      {
        id: "r6",
        userId: "u6",
        userName: "Priya Sharma",
        rating: 5,
        comment:
          "Best immigration consultants in Dubai! They handled my entire family's visa process flawlessly.",
        isVerified: true,
        date: "2024-01-14",
      },
    ],
  },
  {
    id: "5",
    name: "Prime Visa & Passport Solutions",
    category: "Visa & Passport Services",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "One-stop solution for all visa and passport requirements including attestations, renewals, and emergency services.",
    services: [
      "Passport Services",
      "Visa Processing",
      "Document Attestation",
      "Emergency Passport",
      "Consulate Services",
    ],
    address: "Shop 45, Al Karama Shopping Center, Karama, Dubai, UAE",
    phone: "+971-4-396-7788",
    whatsapp: "+971-56-396-7788",
    email: "info@primevisapassport.com",
    licenseNo: "DED-55667",
    rating: 4.4,
    reviewCount: 98,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: false,
    coordinates: { lat: 25.2375, lng: 55.3075 },
    reviews: [
      {
        id: "r7",
        userId: "u7",
        userName: "James Wilson",
        rating: 4,
        comment:
          "Good service for passport renewal. Process was quick and staff was knowledgeable.",
        isVerified: false,
        date: "2024-01-08",
      },
    ],
  },
  {
    id: "6",
    name: "Al Khaleej Immigration Consultancy",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    description:
      "Specialized immigration consultancy providing expert guidance for UAE golden visa, investor visa, and permanent residency applications.",
    services: [
      "Golden Visa",
      "Investor Visa",
      "Permanent Residency",
      "Business Setup",
      "Immigration Law",
    ],
    address: "Office 1101, Conrad Dubai, Sheikh Zayed Road, Dubai, UAE",
    phone: "+971-4-666-9900",
    whatsapp: "+971-52-666-9900",
    email: "info@alkhaleejimmigration.ae",
    website: "https://alkhaleejimmigration.ae",
    licenseNo: "DED-99887",
    rating: 4.8,
    reviewCount: 145,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2282, lng: 55.285 },
    reviews: [
      {
        id: "r8",
        userId: "u8",
        userName: "David Chen",
        rating: 5,
        comment:
          "Exceptional service for golden visa application. Their expertise in immigration law is outstanding.",
        isVerified: true,
        date: "2024-01-22",
      },
      {
        id: "r9",
        userId: "u9",
        userName: "Maria Garcia",
        rating: 5,
        comment:
          "Professional and efficient team. They guided us through the entire investor visa process seamlessly.",
        isVerified: true,
        date: "2024-01-16",
      },
    ],
  },
  {
    id: "7",
    name: "Dubai Document Center",
    category: "Document Clearing / Typing Centers",
    logo: "/api/placeholder/80/80",
    description:
      "Complete document services including typing, translation, attestation, and government liaison for all visa-related paperwork.",
    services: [
      "Document Typing",
      "Translation",
      "Attestation",
      "Embassy Services",
      "Notarization",
    ],
    address: "Ground Floor, Al Rais Shopping Center, Deira, Dubai, UAE",
    phone: "+971-4-227-3344",
    whatsapp: "+971-55-227-3344",
    email: "info@dubaidocumentcenter.com",
    licenseNo: "DED-44556",
    rating: 4.3,
    reviewCount: 76,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2697, lng: 55.3095 },
    reviews: [
      {
        id: "r10",
        userId: "u10",
        userName: "Ali Mohammad",
        rating: 4,
        comment:
          "Reliable service for document processing. Staff is helpful and prices are reasonable.",
        isVerified: false,
        date: "2024-01-11",
      },
    ],
  },
  {
    id: "8",
    name: "Global Visa Hub",
    category: "Visa Agent",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "International visa processing specialists offering services for over 50 countries worldwide.",
    services: [
      "Schengen Visa",
      "UK Visa",
      "US Visa",
      "Canada Visa",
      "Australia Visa",
      "Asia Visa",
    ],
    address: "Office 708, Emaar Business Park, Downtown Dubai, UAE",
    phone: "+971-4-589-7755",
    whatsapp: "+971-50-589-7755",
    email: "info@globalvisahub.com",
    website: "https://globalvisahub.com",
    licenseNo: "DED-77889",
    rating: 4.5,
    reviewCount: 234,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.1972, lng: 55.2744 },
    reviews: [
      {
        id: "r11",
        userId: "u11",
        userName: "Jennifer Lee",
        rating: 5,
        comment:
          "Excellent service for US visa application. Very professional and they know the process well.",
        isVerified: true,
        date: "2024-01-19",
      },
      {
        id: "r12",
        userId: "u12",
        userName: "Ahmed Al Mansouri",
        rating: 4,
        comment:
          "Good experience with Schengen visa. Processing was smooth and communication was clear.",
        isVerified: true,
        date: "2024-01-13",
      },
    ],
  },
  {
    id: "9",
    name: "Express Immigration Solutions",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    description:
      "Fast-track immigration services specializing in urgent visa processing and emergency travel documents.",
    services: [
      "Emergency Visa",
      "Express Processing",
      "Immigration Consultation",
      "Document Preparation",
      "Legal Assistance",
    ],
    address: "Suite 405, The H Dubai, Sheikh Zayed Road, Dubai, UAE",
    phone: "+971-4-778-6655",
    whatsapp: "+971-56-778-6655",
    email: "urgent@expressimmigration.ae",
    website: "https://expressimmigration.ae",
    licenseNo: "DED-88990",
    rating: 4.2,
    reviewCount: 112,
    isVerified: false,
    isScamReported: false,
    importedFromGoogle: false,
    coordinates: { lat: 25.2144, lng: 55.2794 },
    reviews: [
      {
        id: "r13",
        userId: "u13",
        userName: "Sarah Ahmed",
        rating: 4,
        comment:
          "They helped with my emergency visa application. Service was fast but could be more organized.",
        isVerified: false,
        date: "2024-01-09",
      },
    ],
  },
  {
    id: "10",
    name: "Al Dar Visa Services",
    category: "Visa Services",
    logo: "/api/placeholder/80/80",
    description:
      "Trusted visa service provider offering comprehensive solutions for UAE entry visas and residence permits.",
    services: [
      "Entry Visa",
      "Residence Permit",
      "Visa Amendment",
      "Dependent Visa",
      "Visa Consultation",
    ],
    address: "Office 202, Al Seef Building, Bur Dubai, Dubai, UAE",
    phone: "+971-4-359-8822",
    whatsapp: "+971-52-359-8822",
    email: "info@aldarvisaservices.com",
    licenseNo: "DED-66778",
    rating: 4.6,
    reviewCount: 187,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2631, lng: 55.2972 },
    reviews: [
      {
        id: "r14",
        userId: "u14",
        userName: "Carlos Martinez",
        rating: 5,
        comment:
          "Outstanding service! They made my residence permit application very smooth and hassle-free.",
        isVerified: true,
        date: "2024-01-21",
        businessResponse: "Thank you Carlos! We're happy to have assisted you.",
      },
      {
        id: "r15",
        userId: "u15",
        userName: "Yasmin Hassan",
        rating: 4,
        comment:
          "Professional team with good knowledge. Process was transparent and well-managed.",
        isVerified: true,
        date: "2024-01-17",
      },
    ],
  },
  {
    id: "11",
    name: "Emirates Passport Center",
    category: "Visa & Passport Services",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "Specialized passport services including renewals, replacements, and expedited processing for all nationalities.",
    services: [
      "Passport Renewal",
      "Passport Replacement",
      "Child Passport",
      "Expedited Service",
      "Passport Photos",
    ],
    address: "Level 2, Deira City Center, Deira, Dubai, UAE",
    phone: "+971-4-295-7733",
    whatsapp: "+971-55-295-7733",
    email: "services@emiratespassport.com",
    website: "https://emiratespassport.com",
    licenseNo: "DED-55889",
    rating: 4.4,
    reviewCount: 156,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2521, lng: 55.3331 },
    reviews: [
      {
        id: "r16",
        userId: "u16",
        userName: "Mohammed Rashid",
        rating: 5,
        comment:
          "Excellent passport renewal service. Very efficient and professional staff.",
        isVerified: true,
        date: "2024-01-20",
      },
      {
        id: "r17",
        userId: "u17",
        userName: "Linda Thompson",
        rating: 4,
        comment:
          "Good service for child passport. Process was smooth and staff was patient with requirements.",
        isVerified: false,
        date: "2024-01-15",
      },
    ],
  },
  {
    id: "12",
    name: "Metro Typing Center",
    category: "Document Clearing / Typing Centers",
    logo: "/api/placeholder/80/80",
    description:
      "Professional typing and document services center providing accurate and fast processing for all government paperwork.",
    services: [
      "Document Typing",
      "Form Filling",
      "Translation Services",
      "Printing Services",
      "Scanning & Copying",
    ],
    address: "Shop 12, Metro Central Mall, Al Qusais, Dubai, UAE",
    phone: "+971-4-263-4477",
    whatsapp: "+971-56-263-4477",
    email: "info@metrotypingcenter.com",
    licenseNo: "DED-33669",
    rating: 4.1,
    reviewCount: 89,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: false,
    coordinates: { lat: 25.2916, lng: 55.3821 },
    reviews: [
      {
        id: "r18",
        userId: "u18",
        userName: "Raj Kumar",
        rating: 4,
        comment:
          "Reliable typing center with reasonable prices. Good for basic document work.",
        isVerified: false,
        date: "2024-01-12",
      },
    ],
  },
  {
    id: "13",
    name: "Golden Gate Immigration",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    description:
      "Premium immigration consultancy specializing in high-net-worth individual visas and investment immigration programs.",
    services: [
      "Golden Visa Premium",
      "Investment Immigration",
      "Real Estate Visa",
      "Business Immigration",
      "Wealth Management",
    ],
    address: "Penthouse, Four Seasons Resort, Jumeirah Beach Road, Dubai, UAE",
    phone: "+971-4-888-9999",
    whatsapp: "+971-50-888-9999",
    email: "premium@goldengateimmigration.ae",
    website: "https://goldengateimmigration.ae",
    licenseNo: "DED-99001",
    rating: 4.9,
    reviewCount: 87,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2285, lng: 55.2512 },
    reviews: [
      {
        id: "r19",
        userId: "u19",
        userName: "Alexander Petrov",
        rating: 5,
        comment:
          "Exceptional service for high-value immigration. Their expertise in investment visas is unmatched.",
        isVerified: true,
        date: "2024-01-23",
        businessResponse:
          "Thank you Alexander! We appreciate your trust in our premium services.",
      },
      {
        id: "r20",
        userId: "u20",
        userName: "Sophie Laurent",
        rating: 5,
        comment:
          "Professional and discreet service. They handled my golden visa application with utmost care.",
        isVerified: true,
        date: "2024-01-18",
      },
    ],
  },
  {
    id: "14",
    name: "Fast Track Visa Agency",
    category: "Visa Agent",
    logo: "/api/placeholder/80/80",
    description:
      "Express visa processing agency offering same-day and next-day visa services for urgent travel requirements.",
    services: [
      "Same Day Visa",
      "Express Processing",
      "Emergency Travel",
      "Urgent Business Visa",
      "Last Minute Visa",
    ],
    address: "Office 306, Al Mansour Building, Oud Metha, Dubai, UAE",
    phone: "+971-4-337-5566",
    whatsapp: "+971-55-337-5566",
    email: "urgent@fasttrackvisas.com",
    website: "https://fasttrackvisas.com",
    licenseNo: "DED-44772",
    rating: 4.0,
    reviewCount: 156,
    isVerified: false,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2366, lng: 55.3145 },
    reviews: [
      {
        id: "r21",
        userId: "u21",
        userName: "Mark Johnson",
        rating: 4,
        comment:
          "Good for urgent visa needs. They delivered as promised but service could be more polished.",
        isVerified: true,
        date: "2024-01-16",
      },
      {
        id: "r22",
        userId: "u22",
        userName: "Fatma Ali",
        rating: 3,
        comment:
          "Got my visa on time but the process was stressful. Communication could be better.",
        isVerified: false,
        date: "2024-01-10",
      },
    ],
  },
  {
    id: "15",
    name: "Premier Document Solutions",
    category: "Document Clearing / Typing Centers",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "Comprehensive document solutions including attestation, legalization, and embassy services for international use.",
    services: [
      "Document Attestation",
      "Embassy Legalization",
      "Apostille Services",
      "Certificate Authentication",
      "Commercial Documents",
    ],
    address: "Office 504, Khalid Bin Waleed Building, Bur Dubai, Dubai, UAE",
    phone: "+971-4-359-7788",
    whatsapp: "+971-52-359-7788",
    email: "info@premierdocuments.ae",
    website: "https://premierdocuments.ae",
    licenseNo: "DED-77883",
    rating: 4.5,
    reviewCount: 134,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2639, lng: 55.2989 },
    reviews: [
      {
        id: "r23",
        userId: "u23",
        userName: "Hassan Mahmoud",
        rating: 5,
        comment:
          "Excellent attestation service! They handled all my documents professionally and efficiently.",
        isVerified: true,
        date: "2024-01-19",
      },
      {
        id: "r24",
        userId: "u24",
        userName: "Anna Kowalski",
        rating: 4,
        comment:
          "Good service for document legalization. Staff was knowledgeable about requirements.",
        isVerified: true,
        date: "2024-01-14",
      },
    ],
  },
  {
    id: "16",
    name: "Skyline Travel & Visa",
    category: "Travel Agencies (Visa-related)",
    logo: "/api/placeholder/80/80",
    description:
      "Full-service travel agency specializing in visa processing, flight bookings, and travel insurance for global destinations.",
    services: [
      "International Visa",
      "Flight Booking",
      "Travel Insurance",
      "Hotel Booking",
      "Tour Packages",
    ],
    address: "Shop 23, Al Rigga Road, Deira, Dubai, UAE",
    phone: "+971-4-228-9955",
    whatsapp: "+971-56-228-9955",
    email: "travel@skylinevisatravel.com",
    website: "https://skylinevisatravel.com",
    licenseNo: "DED-66994",
    rating: 4.3,
    reviewCount: 198,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2686, lng: 55.3137 },
    reviews: [
      {
        id: "r25",
        userId: "u25",
        userName: "Peter Williams",
        rating: 4,
        comment:
          "Good travel agency with comprehensive services. Visa processing was smooth.",
        isVerified: false,
        date: "2024-01-17",
      },
      {
        id: "r26",
        userId: "u26",
        userName: "Amira Said",
        rating: 5,
        comment:
          "Excellent service for family vacation planning. They handled everything perfectly!",
        isVerified: true,
        date: "2024-01-11",
      },
    ],
  },
  {
    id: "17",
    name: "Crown Immigration Advisors",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    description:
      "Expert immigration advisors providing strategic consultation for complex immigration cases and business migration.",
    services: [
      "Immigration Strategy",
      "Business Migration",
      "Legal Consultation",
      "Appeals & Reviews",
      "Compliance Services",
    ],
    address: "Level 42, Burj Khalifa, Downtown Dubai, UAE",
    phone: "+971-4-999-7777",
    whatsapp: "+971-50-999-7777",
    email: "advisors@crownimmigration.ae",
    website: "https://crownimmigration.ae",
    licenseNo: "DED-88115",
    rating: 4.8,
    reviewCount: 78,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.1972, lng: 55.2744 },
    reviews: [
      {
        id: "r27",
        userId: "u27",
        userName: "Victoria Chen",
        rating: 5,
        comment:
          "Top-tier immigration consultancy. Their strategic approach saved my complex case.",
        isVerified: true,
        date: "2024-01-22",
        businessResponse:
          "Thank you Victoria! Complex cases are our specialty.",
      },
      {
        id: "r28",
        userId: "u28",
        userName: "Ahmed Al Rashid",
        rating: 5,
        comment:
          "Exceptional legal expertise. They provided excellent guidance for my business migration.",
        isVerified: true,
        date: "2024-01-20",
      },
    ],
  },
  {
    id: "18",
    name: "Oasis Visa Center",
    category: "Visa Services",
    logo: "/api/placeholder/80/80",
    description:
      "Reliable visa processing center offering competitive rates and personalized service for all visa types.",
    services: [
      "Tourist Visa",
      "Business Visa",
      "Family Visa",
      "Student Visa",
      "Medical Visa",
    ],
    address: "Office 108, Green Community, Dubai Investment Park, Dubai, UAE",
    phone: "+971-4-885-6644",
    whatsapp: "+971-55-885-6644",
    email: "info@oasisvisacenter.com",
    licenseNo: "DED-55997",
    rating: 4.4,
    reviewCount: 167,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: false,
    coordinates: { lat: 25.0382, lng: 55.1917 },
    reviews: [
      {
        id: "r29",
        userId: "u29",
        userName: "John Davis",
        rating: 4,
        comment:
          "Competitive prices and good service. Helped with my family's tourist visa applications.",
        isVerified: false,
        date: "2024-01-18",
      },
      {
        id: "r30",
        userId: "u30",
        userName: "Layla Ibrahim",
        rating: 5,
        comment:
          "Excellent customer service! They made the visa process very easy to understand.",
        isVerified: true,
        date: "2024-01-13",
      },
    ],
  },
  {
    id: "19",
    name: "Universal Passport Services",
    category: "Visa & Passport Services",
    logo: "/api/placeholder/80/80",
    description:
      "International passport and visa services providing comprehensive solutions for all nationality requirements.",
    services: [
      "Multi-Country Passports",
      "Diplomatic Visa",
      "Official Passport",
      "Emergency Documents",
      "Consular Services",
    ],
    address: "Office 1205, World Trade Center, Sheikh Zayed Road, Dubai, UAE",
    phone: "+971-4-508-7766",
    whatsapp: "+971-52-508-7766",
    email: "info@universalpassport.ae",
    website: "https://universalpassport.ae",
    licenseNo: "DED-77008",
    rating: 4.6,
    reviewCount: 123,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2285, lng: 55.2839 },
    reviews: [
      {
        id: "r31",
        userId: "u31",
        userName: "Robert Anderson",
        rating: 5,
        comment:
          "Professional service for diplomatic visa. They understand complex requirements very well.",
        isVerified: true,
        date: "2024-01-21",
      },
      {
        id: "r32",
        userId: "u32",
        userName: "Noor Al Zahra",
        rating: 4,
        comment:
          "Good service for passport renewal. Process was efficient and staff was helpful.",
        isVerified: true,
        date: "2024-01-16",
      },
    ],
  },
  {
    id: "20",
    name: "Smart Typing Solutions",
    category: "Document Clearing / Typing Centers",
    logo: "/api/placeholder/80/80",
    description:
      "Modern typing center equipped with latest technology for fast and accurate document processing and government services.",
    services: [
      "Digital Typing",
      "Online Forms",
      "Government Portal",
      "E-Services",
      "Digital Signatures",
    ],
    address: "Shop 34, City Walk, Al Wasl, Dubai, UAE",
    phone: "+971-4-432-8899",
    whatsapp: "+971-56-432-8899",
    email: "info@smarttypingsolutions.com",
    website: "https://smarttypingsolutions.com",
    licenseNo: "DED-66119",
    rating: 4.2,
    reviewCount: 94,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: false,
    coordinates: { lat: 25.2103, lng: 55.2648 },
    reviews: [
      {
        id: "r33",
        userId: "u33",
        userName: "Tech User",
        rating: 4,
        comment:
          "Modern setup with good technology. Fast service for digital document processing.",
        isVerified: false,
        date: "2024-01-14",
      },
    ],
  },
  // Continue with more businesses...
  {
    id: "21",
    name: "Elite Immigration Partners",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "Exclusive immigration consultancy serving high-profile clients and multinational corporations with complex immigration needs.",
    services: [
      "Corporate Immigration",
      "Executive Visas",
      "Diplomatic Relations",
      "Government Liaison",
      "Policy Consultation",
    ],
    address:
      "Presidential Suite, Address Downtown, Mohammed Bin Rashid Boulevard, Dubai, UAE",
    phone: "+971-4-999-8888",
    whatsapp: "+971-50-999-8888",
    email: "elite@immigrationpartners.ae",
    website: "https://eliteimmigrationpartners.ae",
    licenseNo: "DED-99228",
    rating: 4.9,
    reviewCount: 45,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.1955, lng: 55.2719 },
    reviews: [
      {
        id: "r34",
        userId: "u34",
        userName: "CEO Executive",
        rating: 5,
        comment:
          "Unparalleled service for corporate immigration needs. Their connections and expertise are invaluable.",
        isVerified: true,
        date: "2024-01-24",
        businessResponse:
          "Thank you for trusting us with your organization's immigration needs.",
      },
    ],
  },
  {
    id: "22",
    name: "Horizon Visa Processing",
    category: "Visa Agent",
    logo: "/api/placeholder/80/80",
    description:
      "Comprehensive visa processing agency with expertise in multiple countries and specialized visa categories.",
    services: [
      "Multi-Country Visa",
      "Group Visa",
      "Event Visa",
      "Conference Visa",
      "Exhibition Visa",
    ],
    address:
      "Office 601, Emirates NBD Building, Baniyas Road, Deira, Dubai, UAE",
    phone: "+971-4-266-7755",
    whatsapp: "+971-55-266-7755",
    email: "info@horizonvisaprocessing.com",
    website: "https://horizonvisaprocessing.com",
    licenseNo: "DED-55339",
    rating: 4.3,
    reviewCount: 189,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2644, lng: 55.3065 },
    reviews: [
      {
        id: "r35",
        userId: "u35",
        userName: "Event Manager",
        rating: 4,
        comment:
          "Good service for group visa processing. They handled our conference attendees efficiently.",
        isVerified: true,
        date: "2024-01-19",
      },
      {
        id: "r36",
        userId: "u36",
        userName: "Travel Coordinator",
        rating: 5,
        comment:
          "Excellent for multi-country visa applications. Save us a lot of time and effort.",
        isVerified: false,
        date: "2024-01-15",
      },
    ],
  },
  {
    id: "23",
    name: "Capital Document Services",
    category: "Document Clearing / Typing Centers",
    logo: "/api/placeholder/80/80",
    description:
      "Premium document services center specializing in high-value document processing and executive services.",
    services: [
      "Executive Document Service",
      "VIP Processing",
      "Courier Services",
      "Document Storage",
      "Confidential Handling",
    ],
    address: "Level 25, Emirates Towers, Sheikh Zayed Road, Dubai, UAE",
    phone: "+971-4-319-8877",
    whatsapp: "+971-52-319-8877",
    email: "vip@capitaldocuments.ae",
    website: "https://capitaldocuments.ae",
    licenseNo: "DED-88447",
    rating: 4.7,
    reviewCount: 67,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2183, lng: 55.2671 },
    reviews: [
      {
        id: "r37",
        userId: "u37",
        userName: "Business Executive",
        rating: 5,
        comment:
          "Premium service worth the price. Confidential handling and VIP treatment for important documents.",
        isVerified: true,
        date: "2024-01-21",
      },
    ],
  },
  {
    id: "24",
    name: "Gateway Immigration Hub",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    description:
      "Central immigration hub providing comprehensive immigration solutions and ongoing support for expatriate families.",
    services: [
      "Family Immigration",
      "Expat Support",
      "School Enrollment",
      "Healthcare Registration",
      "Banking Assistance",
    ],
    address: "Building 3, Dubai International Financial Centre, Dubai, UAE",
    phone: "+971-4-777-6655",
    whatsapp: "+971-50-777-6655",
    email: "families@gatewayimmigration.ae",
    website: "https://gatewayimmigration.ae",
    licenseNo: "DED-66558",
    rating: 4.6,
    reviewCount: 234,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2138, lng: 55.2792 },
    reviews: [
      {
        id: "r38",
        userId: "u38",
        userName: "Expat Family",
        rating: 5,
        comment:
          "Comprehensive support for our family's relocation. They helped with everything from visas to school enrollment.",
        isVerified: true,
        date: "2024-01-20",
        businessResponse:
          "Welcome to Dubai! We're glad we could help make your transition smooth.",
      },
      {
        id: "r39",
        userId: "u39",
        userName: "International Executive",
        rating: 4,
        comment:
          "Good overall service for corporate relocation. Their expat support package is quite comprehensive.",
        isVerified: true,
        date: "2024-01-17",
      },
    ],
  },
  {
    id: "25",
    name: "Prestige Passport & Visa",
    category: "Visa & Passport Services",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "Luxury passport and visa services offering white-glove service for discerning clientele and corporate executives.",
    services: [
      "Concierge Visa Service",
      "Private Appointments",
      "Executive Assistance",
      "Luxury Processing",
      "Personal Consultant",
    ],
    address: "Royal Suite, Atlantis The Palm, Palm Jumeirah, Dubai, UAE",
    phone: "+971-4-426-2000",
    whatsapp: "+971-50-426-2000",
    email: "concierge@prestigepassportvisa.com",
    website: "https://prestigepassportvisa.com",
    licenseNo: "DED-99556",
    rating: 4.8,
    reviewCount: 56,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: false,
    coordinates: { lat: 25.1303, lng: 55.1162 },
    reviews: [
      {
        id: "r40",
        userId: "u40",
        userName: "VIP Client",
        rating: 5,
        comment:
          "Exceptional white-glove service. Personal consultant made the entire process effortless.",
        isVerified: true,
        date: "2024-01-23",
      },
      {
        id: "r41",
        userId: "u41",
        userName: "Corporate Executive",
        rating: 5,
        comment:
          "Premium service that justifies the cost. Private appointments and executive assistance are outstanding.",
        isVerified: true,
        date: "2024-01-18",
      },
    ],
  },
  // Adding more businesses to reach closer to 50...
  {
    id: "26",
    name: "Miracle Visa Center",
    category: "Visa Services",
    logo: "/api/placeholder/80/80",
    description:
      "Specialized visa center focusing on difficult cases and visa appeals with high success rates.",
    services: [
      "Visa Appeals",
      "Difficult Cases",
      "Rejected Visa Review",
      "Legal Representation",
      "Documentation Review",
    ],
    address: "Office 702, Al Habtoor Business Tower, Dubai Marina, Dubai, UAE",
    phone: "+971-4-447-9988",
    whatsapp: "+971-55-447-9988",
    email: "appeals@miraclevisacenter.com",
    website: "https://miraclevisacenter.com",
    licenseNo: "DED-77449",
    rating: 4.1,
    reviewCount: 78,
    isVerified: false,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.0776, lng: 55.139 },
    reviews: [
      {
        id: "r42",
        userId: "u42",
        userName: "Grateful Client",
        rating: 5,
        comment:
          "They saved my rejected visa case! Excellent legal expertise and persistence.",
        isVerified: true,
        date: "2024-01-22",
      },
      {
        id: "r43",
        userId: "u43",
        userName: "Second Chance",
        rating: 4,
        comment:
          "Good for difficult cases. They don't give up easily and know the system well.",
        isVerified: false,
        date: "2024-01-16",
      },
    ],
  },
  {
    id: "27",
    name: "Digital Immigration Services",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    description:
      "Tech-forward immigration consultancy offering online consultations and digital-first immigration solutions.",
    services: [
      "Online Consultation",
      "Digital Applications",
      "Virtual Meetings",
      "AI-Assisted Processing",
      "Mobile App Support",
    ],
    address: "Office 1501, One Central, World Trade Center, Dubai, UAE",
    phone: "+971-4-567-8899",
    whatsapp: "+971-56-567-8899",
    email: "digital@immigrationservices.ae",
    website: "https://digitalimmigration.ae",
    licenseNo: "DED-88667",
    rating: 4.3,
    reviewCount: 145,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2285, lng: 55.2839 },
    reviews: [
      {
        id: "r44",
        userId: "u44",
        userName: "Tech Professional",
        rating: 4,
        comment:
          "Love the digital approach! Online consultations are convenient and their app is user-friendly.",
        isVerified: true,
        date: "2024-01-20",
      },
      {
        id: "r45",
        userId: "u45",
        userName: "Remote Worker",
        rating: 5,
        comment:
          "Perfect for busy professionals. Virtual meetings and digital processing made everything easy.",
        isVerified: true,
        date: "2024-01-14",
      },
    ],
  },
  {
    id: "28",
    name: "Heritage Document Center",
    category: "Document Clearing / Typing Centers",
    logo: "/api/placeholder/80/80",
    description:
      "Traditional document center with decades of experience in government procedures and official documentation.",
    services: [
      "Traditional Documentation",
      "Government Liaison",
      "Official Procedures",
      "Legacy Document Handling",
      "Experienced Staff",
    ],
    address: "Shop 8, Old Souk, Bur Dubai, Dubai, UAE",
    phone: "+971-4-353-6677",
    whatsapp: "+971-55-353-6677",
    email: "heritage@documentcenter.ae",
    licenseNo: "DED-33884",
    rating: 4.0,
    reviewCount: 156,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2631, lng: 55.2972 },
    reviews: [
      {
        id: "r46",
        userId: "u46",
        userName: "Long-time Resident",
        rating: 4,
        comment:
          "Old-school service with experienced staff who know all the procedures by heart.",
        isVerified: false,
        date: "2024-01-18",
      },
      {
        id: "r47",
        userId: "u47",
        userName: "Government Worker",
        rating: 4,
        comment:
          "They've been around forever and know how to handle complex government documents.",
        isVerified: true,
        date: "2024-01-12",
      },
    ],
  },
  {
    id: "29",
    name: "Swift Travel Solutions",
    category: "Travel Agencies (Visa-related)",
    logo: "/api/placeholder/80/80",
    description:
      "Dynamic travel agency specializing in last-minute travel arrangements and emergency visa processing.",
    services: [
      "Last Minute Travel",
      "Emergency Booking",
      "24/7 Support",
      "Crisis Management",
      "Urgent Arrangements",
    ],
    address: "Office 404, Clock Tower, Deira, Dubai, UAE",
    phone: "+971-4-224-7788",
    whatsapp: "+971-56-224-7788",
    email: "urgent@swifttravelsolutions.com",
    website: "https://swifttravelsolutions.com",
    licenseNo: "DED-55992",
    rating: 4.2,
    reviewCount: 167,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: false,
    coordinates: { lat: 25.2697, lng: 55.3095 },
    reviews: [
      {
        id: "r48",
        userId: "u48",
        userName: "Business Traveler",
        rating: 4,
        comment:
          "Excellent for emergency travel situations. Their 24/7 support really works!",
        isVerified: true,
        date: "2024-01-19",
      },
      {
        id: "r49",
        userId: "u49",
        userName: "Crisis Manager",
        rating: 5,
        comment:
          "Saved our company trip when original plans fell through. Highly responsive team.",
        isVerified: true,
        date: "2024-01-13",
      },
    ],
  },
  {
    id: "30",
    name: "Supreme Immigration Authority",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/400/200",
    description:
      "Authoritative immigration consultancy with former government officials providing insider knowledge and expertise.",
    services: [
      "Government Relations",
      "Policy Interpretation",
      "Regulatory Compliance",
      "Strategic Planning",
      "High-Level Consultation",
    ],
    address: "Executive Floor, Dubai Chamber Building, Bur Dubai, Dubai, UAE",
    phone: "+971-4-359-9966",
    whatsapp: "+971-50-359-9966",
    email: "authority@supremeimmigration.ae",
    website: "https://supremeimmigration.ae",
    licenseNo: "DED-99773",
    rating: 4.7,
    reviewCount: 89,
    isVerified: true,
    isScamReported: false,
    importedFromGoogle: true,
    coordinates: { lat: 25.2631, lng: 55.2972 },
    reviews: [
      {
        id: "r50",
        userId: "u50",
        userName: "Corporate Counsel",
        rating: 5,
        comment:
          "Unmatched expertise in immigration law and policy. Their government connections are invaluable.",
        isVerified: true,
        date: "2024-01-21",
        businessResponse:
          "Thank you! Our team's government experience makes all the difference.",
      },
    ],
  },
];

export const featuredBusinesses = sampleBusinesses.filter(
  (business) => business.isVerified && business.rating >= 4.5,
);

export const dubaiZones = [
  "Business Bay",
  "Downtown Dubai",
  "Dubai Marina",
  "Deira",
  "Bur Dubai",
  "Jumeirah",
  "Sheikh Zayed Road",
  "Dubai International City",
  "Karama",
  "Al Barsha",
  "Jebel Ali",
];
