// India Visa Consultant Directory - Complete Data Structure

export interface Business {
  id: string;
  name: string;
  category: BusinessCategory;
  logo?: string;
  coverImage?: string;
  gallery?: string[];
  description: string;
  services: string[];
  address: string;
  city: string;
  state: string;
  pincode: string;
  phone: string;
  whatsapp?: string;
  email: string;
  website?: string;
  licenseNo?: string;
  rating: number;
  reviewCount: number;
  isVerified: boolean;
  isFeatured: boolean;
  plan: "free" | "premium" | "business";
  establishedYear?: number;
  successRate?: number;
  languages: string[];
  specializations: string[];
  countriesServed: string[];
  coordinates: {
    lat: number;
    lng: number;
  };
  openingHours?: {
    [key: string]: string;
  };
  paymentMethods: string[];
  reviews: Review[];
  socialMedia?: {
    facebook?: string;
    instagram?: string;
    linkedin?: string;
    twitter?: string;
  };
}

export interface Review {
  id: string;
  userId: string;
  userName: string;
  userAvatar?: string;
  rating: number;
  comment: string;
  visaType?: string;
  country?: string;
  images?: string[];
  isVerified: boolean;
  date: string;
  businessResponse?: string;
}

export type BusinessCategory =
  | "Student Visa Consultants"
  | "Work Visa Consultants"
  | "Tourist Visa Services"
  | "Business Visa Services"
  | "Immigration Lawyers"
  | "Study Abroad Consultants"
  | "PR & Citizenship Services"
  | "Visa Documentation Services"
  | "Embassy Services"
  | "Visa Interview Preparation"
  | "Language Training Centers"
  | "Education Consultants";

export const businessCategories: BusinessCategory[] = [
  "Student Visa Consultants",
  "Work Visa Consultants",
  "Tourist Visa Services",
  "Business Visa Services",
  "Immigration Lawyers",
  "Study Abroad Consultants",
  "PR & Citizenship Services",
  "Visa Documentation Services",
  "Embassy Services",
  "Visa Interview Preparation",
  "Language Training Centers",
  "Education Consultants",
];

// Category slugs for URL routing
export const categoryMapping: Record<string, string> = {
  "study-abroad": "Study Abroad Consultants",
  "immigration-consultants": "Immigration Lawyers",
  "visa-consultants": "Student Visa Consultants",
  "work-permit": "Work Visa Consultants",
  "visa-services": "Visa Documentation Services",
  "immigration-services": "PR & Citizenship Services",
  "overseas-services": "Embassy Services",
  "education-services": "Education Consultants",
};

export const categorySlugs = Object.keys(categoryMapping);

export const visaTypes = [
  "Student Visa",
  "Work Visa",
  "Tourist Visa",
  "Business Visa",
  "Transit Visa",
  "Medical Visa",
  "Conference Visa",
  "Employment Visa",
  "Dependent Visa",
  "Permanent Residency",
] as const;

export type VisaType = (typeof visaTypes)[number];

// Major Indian Cities
export const indianCities = [
  // Tier 1 Cities
  "Delhi",
  "Mumbai",
  "Bangalore",
  "Chennai",
  "Hyderabad",
  "Kolkata",
  "Pune",
  "Ahmedabad",

  // Popular Metro Cities
  "Jaipur",
  "Lucknow",
  "Indore",
  "Chandigarh",
  "Gurgaon",
  "Noida",
  "Dehradun",
  "Kochi", // Kerala major city

  // Other Major Cities
  "Surat",
  "Kanpur",
  "Nagpur",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan-Dombivali",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
];

// Dubai zones for backward compatibility (can be removed later)
export const dubaiZones = [
  "Business Bay",
  "Downtown Dubai",
  "Dubai Marina",
  "JLT",
  "DIFC",
  "Deira",
  "Bur Dubai",
  "Jumeirah",
];

// Keep UAE cities for backward compatibility
export const uaeCities = indianCities;

// Sample Businesses
export const sampleBusinesses: Business[] = [
  {
    id: "1",
    name: "Delhi Global Visa Consultants",
    category: "Student Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    gallery: [
      "/api/placeholder/300/200",
      "/api/placeholder/300/200",
      "/api/placeholder/300/200",
    ],
    description:
      "Leading student visa consultancy in Delhi with 15+ years of experience. We specialize in admissions and visa assistance for USA, Canada, UK, Australia, and European universities.",
    services: [
      "Student Visa for USA",
      "Student Visa for Canada",
      "Student Visa for UK",
      "Student Visa for Australia",
      "University Admissions",
      "Scholarship Guidance",
      "IELTS/TOEFL Preparation",
      "SOP Writing",
      "Document Verification",
    ],
    address: "A-25, Connaught Place, Central Delhi",
    city: "Delhi",
    state: "Delhi",
    pincode: "110001",
    phone: "+91-11-4567-8901",
    whatsapp: "+91-98765-43210",
    email: "info@delhiglobalvisa.com",
    website: "https://delhiglobalvisa.com",
    licenseNo: "EDU-DL-2024-001",
    rating: 4.8,
    reviewCount: 234,
    isVerified: true,
    isFeatured: true,
    plan: "business",
    establishedYear: 2009,
    successRate: 95,
    languages: ["Hindi", "English", "Punjabi"],
    specializations: ["USA F1 Visa", "Canada Study Permits", "UK Tier 4"],
    countriesServed: ["USA", "Canada", "UK", "Australia", "Germany", "France"],
    coordinates: { lat: 28.6328, lng: 77.2197 },
    openingHours: {
      Monday: "9:00 AM - 7:00 PM",
      Tuesday: "9:00 AM - 7:00 PM",
      Wednesday: "9:00 AM - 7:00 PM",
      Thursday: "9:00 AM - 7:00 PM",
      Friday: "9:00 AM - 7:00 PM",
      Saturday: "10:00 AM - 5:00 PM",
      Sunday: "Closed",
    },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [
      {
        id: "r1",
        userId: "u1",
        userName: "Priya Sharma",
        userAvatar: "/api/placeholder/40/40",
        rating: 5,
        comment:
          "Excellent service! Got my USA student visa approved in just 3 weeks. The team was very professional and guided me throughout the process.",
        visaType: "Student Visa",
        country: "USA",
        isVerified: true,
        date: "2024-01-15",
      },
      {
        id: "r2",
        userId: "u2",
        userName: "Rahul Kumar",
        rating: 5,
        comment:
          "Best consultancy in Delhi! They helped me get admission to University of Toronto and visa was approved without any hassle.",
        visaType: "Student Visa",
        country: "Canada",
        isVerified: true,
        date: "2024-01-10",
      },
    ],
    socialMedia: {
      facebook: "https://facebook.com/delhiglobalvisa",
      instagram: "https://instagram.com/delhiglobalvisa",
      linkedin: "https://linkedin.com/company/delhiglobalvisa",
    },
  },
  {
    id: "2",
    name: "Mumbai Immigration Hub",
    category: "Work Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    gallery: ["/api/placeholder/300/200"],
    description:
      "Premier work visa consultancy in Mumbai specializing in employment-based immigration to Canada, Australia, and European countries.",
    services: [
      "Express Entry Canada",
      "Australia PR",
      "Germany Work Visa",
      "UK Skilled Worker Visa",
      "Job Search Assistance",
      "Resume Building",
      "Interview Preparation",
    ],
    address: "Office 15, Nariman Point, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400021",
    phone: "+91-22-6789-0123",
    whatsapp: "+91-97654-32109",
    email: "contact@mumbaiimmigration.com",
    website: "https://mumbaiimmigration.com",
    licenseNo: "IMM-MH-2024-002",
    rating: 4.7,
    reviewCount: 189,
    isVerified: true,
    isFeatured: true,
    plan: "premium",
    establishedYear: 2012,
    successRate: 92,
    languages: ["Hindi", "English", "Marathi", "Gujarati"],
    specializations: ["Express Entry", "Australia PR", "Europe Work Permits"],
    countriesServed: ["Canada", "Australia", "Germany", "Netherlands", "UK"],
    coordinates: { lat: 18.9322, lng: 72.8264 },
    openingHours: {
      Monday: "9:30 AM - 6:30 PM",
      Tuesday: "9:30 AM - 6:30 PM",
      Wednesday: "9:30 AM - 6:30 PM",
      Thursday: "9:30 AM - 6:30 PM",
      Friday: "9:30 AM - 6:30 PM",
      Saturday: "10:00 AM - 4:00 PM",
      Sunday: "Closed",
    },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking", "Cheque"],
    reviews: [
      {
        id: "r3",
        userId: "u3",
        userName: "Amit Patel",
        rating: 5,
        comment:
          "Outstanding service for Canada PR. They handled everything professionally and I got my invitation in 6 months!",
        visaType: "Work Visa",
        country: "Canada",
        isVerified: true,
        date: "2024-01-08",
      },
    ],
  },
  {
    id: "3",
    name: "Bangalore Study Abroad Center",
    category: "Study Abroad Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Premier study abroad consultancy in Bangalore helping students achieve their dreams of international education.",
    services: [
      "University Selection",
      "Application Processing",
      "Visa Assistance",
      "Scholarship Guidance",
      "Test Preparation",
      "Pre-departure Orientation",
    ],
    address: "MG Road, Brigade Towers, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560001",
    phone: "+91-80-1234-5678",
    email: "info@bangalorestudyabroad.com",
    licenseNo: "EDU-KA-2024-003",
    rating: 4.6,
    reviewCount: 156,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    establishedYear: 2015,
    successRate: 88,
    languages: ["English", "Hindi", "Kannada", "Tamil"],
    specializations: ["IT Programs", "Engineering", "Business Studies"],
    countriesServed: ["USA", "UK", "Australia", "Canada", "Germany"],
    coordinates: { lat: 12.9716, lng: 77.5946 },
    paymentMethods: ["Card", "UPI", "Net Banking"],
    reviews: [],
  },
  // Mumbai businesses
  {
    id: "4",
    name: "Mumbai Visa Solutions",
    category: "Student Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Premier visa consultancy in Mumbai offering comprehensive student visa services for top universities worldwide.",
    services: [
      "Student Visa for USA",
      "Student Visa for UK",
      "Student Visa for Canada",
      "IELTS Preparation",
    ],
    address: "Nariman Point, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400021",
    phone: "+91-22-1234-5678",
    email: "info@mumbaivivasolutions.com",
    rating: 4.5,
    reviewCount: 89,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Hindi", "English", "Marathi"],
    specializations: ["Student Visas", "University Admissions"],
    countriesServed: ["USA", "UK", "Canada", "Australia"],
    coordinates: { lat: 19.076, lng: 72.8777 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },
  // Jaipur businesses
  {
    id: "5",
    name: "Jaipur Immigration Services",
    category: "Work Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Specialized work visa consultancy in Jaipur with expertise in global employment opportunities.",
    services: [
      "Work Visa for Canada",
      "Work Visa for Australia",
      "Work Visa for Germany",
      "Job Placement",
    ],
    address: "C-Scheme, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302001",
    phone: "+91-141-123-4567",
    email: "contact@jaipurimmigration.com",
    rating: 4.3,
    reviewCount: 67,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Hindi", "English", "Rajasthani"],
    specializations: ["Work Visas", "Job Placement"],
    countriesServed: ["Canada", "Australia", "Germany", "UAE"],
    coordinates: { lat: 26.9124, lng: 75.7873 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },
  // Lucknow businesses
  {
    id: "6",
    name: "Lucknow Global Consultants",
    category: "Tourist Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Leading tourist visa specialists in Lucknow helping families and individuals explore the world.",
    services: [
      "Tourist Visa for Europe",
      "Tourist Visa for USA",
      "Tourist Visa for Singapore",
      "Travel Insurance",
    ],
    address: "Hazratganj, Lucknow",
    city: "Lucknow",
    state: "Uttar Pradesh",
    pincode: "226001",
    phone: "+91-522-123-4567",
    email: "info@lucknowglobal.com",
    rating: 4.4,
    reviewCount: 78,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Hindi", "English", "Urdu"],
    specializations: ["Tourist Visas", "Travel Insurance"],
    countriesServed: ["Europe", "USA", "Singapore", "Thailand"],
    coordinates: { lat: 26.8467, lng: 80.9462 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },
  // Chandigarh businesses
  {
    id: "7",
    name: "Chandigarh Study Abroad",
    category: "Student Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Trusted study abroad consultancy in Chandigarh with successful track record in student placements.",
    services: [
      "Student Visa for UK",
      "Student Visa for Australia",
      "Student Visa for New Zealand",
      "Scholarship Guidance",
    ],
    address: "Sector 17, Chandigarh",
    city: "Chandigarh",
    state: "Chandigarh",
    pincode: "160017",
    phone: "+91-172-123-4567",
    email: "admissions@chandigarhstudyabroad.com",
    rating: 4.6,
    reviewCount: 92,
    isVerified: true,
    isFeatured: false,
    plan: "business",
    languages: ["Hindi", "English", "Punjabi"],
    specializations: ["Student Visas", "Scholarship Guidance"],
    countriesServed: ["UK", "Australia", "New Zealand", "Canada"],
    coordinates: { lat: 30.7333, lng: 76.7794 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },
  // Gurgaon businesses
  {
    id: "8",
    name: "Gurgaon Immigration Hub",
    category: "Business Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Corporate immigration solutions in Gurgaon specializing in business visas and investor programs.",
    services: [
      "Business Visa for USA",
      "Investor Visa for Canada",
      "Business Visa for UK",
      "Corporate Immigration",
    ],
    address: "DLF Phase 1, Gurgaon",
    city: "Gurgaon",
    state: "Haryana",
    pincode: "122002",
    phone: "+91-124-123-4567",
    email: "business@gurgaonimmigration.com",
    rating: 4.7,
    reviewCount: 134,
    isVerified: true,
    isFeatured: false,
    plan: "business",
    languages: ["Hindi", "English"],
    specializations: ["Business Visas", "Investor Programs"],
    countriesServed: ["USA", "Canada", "UK", "Australia"],
    coordinates: { lat: 28.4595, lng: 77.0266 },
    paymentMethods: ["Card", "UPI", "Net Banking"],
    reviews: [],
  },
  // Noida businesses
  {
    id: "9",
    name: "Noida Visa Center",
    category: "Student Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Modern visa consultancy in Noida providing end-to-end student visa services with technology integration.",
    services: [
      "Student Visa for USA",
      "Student Visa for Germany",
      "Student Visa for France",
      "Digital Documentation",
    ],
    address: "Sector 18, Noida",
    city: "Noida",
    state: "Uttar Pradesh",
    pincode: "201301",
    phone: "+91-120-123-4567",
    email: "support@noidavisacenter.com",
    rating: 4.5,
    reviewCount: 156,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Hindi", "English"],
    specializations: ["Student Visas", "Digital Documentation"],
    countriesServed: ["USA", "Germany", "France", "Netherlands"],
    coordinates: { lat: 28.5355, lng: 77.391 },
    paymentMethods: ["Card", "UPI", "Net Banking"],
    reviews: [],
  },
  // Kochi businesses
  {
    id: "10",
    name: "Kerala Global Services",
    category: "Work Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Premier immigration consultancy in Kerala specializing in Gulf country work visas and placements.",
    services: [
      "Work Visa for UAE",
      "Work Visa for Saudi Arabia",
      "Work Visa for Qatar",
      "Gulf Job Placement",
    ],
    address: "Marine Drive, Kochi",
    city: "Kochi",
    state: "Kerala",
    pincode: "682031",
    phone: "+91-484-123-4567",
    email: "info@keralaglobalservices.com",
    rating: 4.4,
    reviewCount: 167,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Malayalam", "English", "Hindi"],
    specializations: ["Gulf Work Visas", "Job Placement"],
    countriesServed: ["UAE", "Saudi Arabia", "Qatar", "Kuwait"],
    coordinates: { lat: 9.9312, lng: 76.2673 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },

  // Additional Kerala businesses for better regional coverage
  {
    id: "kerala-2",
    name: "Malabar Immigration Services",
    category: "Student Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Leading education consultancy in Kerala for international studies and student visa services.",
    services: [
      "Student Visa for USA",
      "Student Visa for Canada",
      "Student Visa for UK",
      "IELTS Coaching",
    ],
    address: "MG Road, Thiruvananthapuram",
    city: "Thiruvananthapuram",
    state: "Kerala",
    pincode: "695001",
    phone: "+91-471-234-5678",
    email: "info@malabarimmigration.com",
    rating: 4.6,
    reviewCount: 143,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Malayalam", "English", "Hindi"],
    specializations: ["Student Visas", "Study Abroad"],
    countriesServed: ["USA", "Canada", "UK", "Australia"],
    coordinates: { lat: 8.5241, lng: 76.9366 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },
  {
    id: "kerala-3",
    name: "Kerala Study Abroad Consultants",
    category: "Study Abroad Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Premier study abroad consultancy in Kochi helping students achieve their international education dreams.",
    services: [
      "Study Abroad Counseling",
      "University Applications",
      "Scholarship Guidance",
      "Visa Documentation",
    ],
    address: "Panampilly Nagar, Kochi",
    city: "Kochi",
    state: "Kerala",
    pincode: "682036",
    phone: "+91-484-345-6789",
    email: "info@keralastudyabroad.com",
    rating: 4.5,
    reviewCount: 189,
    isVerified: true,
    isFeatured: false,
    plan: "business",
    languages: ["Malayalam", "English", "Tamil"],
    specializations: ["Study Abroad", "University Admissions"],
    countriesServed: ["USA", "Canada", "UK", "Australia", "Germany"],
    coordinates: { lat: 9.9816, lng: 76.2999 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },
  {
    id: "kerala-4",
    name: "South Indian Education Hub",
    category: "Education Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Comprehensive education consultancy serving Kerala and Tamil Nadu with expert guidance for students.",
    services: [
      "Career Counseling",
      "Course Selection",
      "College Admissions",
      "Educational Loans",
    ],
    address: "Kozhikode Beach Road",
    city: "Kozhikode",
    state: "Kerala",
    pincode: "673001",
    phone: "+91-495-456-7890",
    email: "info@southindianedulhub.com",
    rating: 4.3,
    reviewCount: 98,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Malayalam", "English", "Tamil", "Hindi"],
    specializations: ["Education Counseling", "Career Guidance"],
    countriesServed: ["India", "USA", "Canada", "UK"],
    coordinates: { lat: 11.2588, lng: 75.7804 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },

  // Tamil Nadu businesses for better South Indian coverage
  {
    id: "tn-1",
    name: "Coimbatore Study Centre",
    category: "Study Abroad Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Leading study abroad consultancy in Coimbatore specializing in US, UK, and Canadian universities.",
    services: [
      "University Selection",
      "Application Assistance",
      "Visa Guidance",
      "Pre-departure Support",
    ],
    address: "RS Puram, Coimbatore",
    city: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641002",
    phone: "+91-422-234-5678",
    email: "info@coimbatorestudycentre.com",
    rating: 4.4,
    reviewCount: 167,
    isVerified: true,
    isFeatured: false,
    plan: "business",
    languages: ["Tamil", "English", "Hindi"],
    specializations: ["Study Abroad", "University Applications"],
    countriesServed: ["USA", "Canada", "UK", "Australia", "Germany"],
    coordinates: { lat: 11.0168, lng: 76.9558 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },
  {
    id: "tn-2",
    name: "Chennai Global Education",
    category: "Education Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Comprehensive education consultancy in Chennai providing guidance for domestic and international education.",
    services: [
      "Career Counseling",
      "Course Selection",
      "College Admissions",
      "Scholarship Guidance",
    ],
    address: "T. Nagar, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600017",
    phone: "+91-44-345-6789",
    email: "info@chennaiglobaledu.com",
    rating: 4.6,
    reviewCount: 234,
    isVerified: true,
    isFeatured: true,
    plan: "business",
    languages: ["Tamil", "English", "Telugu", "Hindi"],
    specializations: ["Education Counseling", "International Education"],
    countriesServed: ["India", "USA", "Canada", "UK", "Australia"],
    coordinates: { lat: 13.0827, lng: 80.2707 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },
  {
    id: "tn-3",
    name: "Madurai Education Hub",
    category: "Student Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Trusted student visa consultancy in Madurai helping students secure visas for international education.",
    services: [
      "Student Visa Processing",
      "Document Preparation",
      "Interview Coaching",
      "Post-visa Support",
    ],
    address: "Anna Nagar, Madurai",
    city: "Madurai",
    state: "Tamil Nadu",
    pincode: "625020",
    phone: "+91-452-456-7890",
    email: "info@maduraieducationhub.com",
    rating: 4.3,
    reviewCount: 145,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Tamil", "English", "Hindi"],
    specializations: ["Student Visas", "Study Abroad"],
    countriesServed: ["USA", "Canada", "UK", "Australia", "New Zealand"],
    coordinates: { lat: 9.9252, lng: 78.1198 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },

  // Additional Rajasthan businesses for Kota, Jodhpur regional coverage
  {
    id: "raj-1",
    name: "Rajasthan Study Abroad Centre",
    category: "Study Abroad Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description: "Leading study abroad consultancy in Jaipur serving students across Rajasthan for international education.",
    services: [
      "University Selection",
      "Application Assistance",
      "Visa Processing",
      "Pre-departure Guidance",
    ],
    address: "MI Road, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302001",
    phone: "+91-141-345-6789",
    email: "info@rajasthanstudyabroad.com",
    rating: 4.5,
    reviewCount: 178,
    isVerified: true,
    isFeatured: false,
    plan: "business",
    languages: ["Hindi", "English", "Rajasthani"],
    specializations: ["Study Abroad", "International Education"],
    countriesServed: ["USA", "Canada", "UK", "Australia", "Germany"],
    coordinates: { lat: 26.9124, lng: 75.7873 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },
  {
    id: "raj-2",
    name: "Pink City Education Consultants",
    category: "Education Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description: "Comprehensive education consultancy in Jaipur providing guidance for both domestic and international education opportunities.",
    services: [
      "Career Counseling",
      "Course Selection",
      "College Admissions",
      "Scholarship Guidance",
    ],
    address: "Tonk Road, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302018",
    phone: "+91-141-456-7890",
    email: "info@pinkcityeducation.com",
    rating: 4.4,
    reviewCount: 145,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Hindi", "English", "Rajasthani"],
    specializations: ["Education Counseling", "Career Guidance"],
    countriesServed: ["India", "USA", "Canada", "UK"],
    coordinates: { lat: 26.8467, lng: 75.8063 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },
  {
    id: "raj-3",
    name: "Desert State Visa Services",
    category: "Student Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description: "Trusted student visa consultancy in Jaipur helping students from Rajasthan secure international education visas.",
    services: [
      "Student Visa Processing",
      "Document Preparation",
      "Interview Coaching",
      "Post-visa Support",
    ],
    address: "Vaishali Nagar, Jaipur",
    city: "Jaipur",
    state: "Rajasthan",
    pincode: "302021",
    phone: "+91-141-567-8901",
    email: "info@desertstatevisas.com",
    rating: 4.6,
    reviewCount: 167,
    isVerified: true,
    isFeatured: true,
    plan: "business",
    languages: ["Hindi", "English", "Rajasthani", "Gujarati"],
    specializations: ["Student Visas", "Study Abroad"],
    countriesServed: ["USA", "Canada", "UK", "Australia", "New Zealand"],
    coordinates: { lat: 26.9157, lng: 75.7672 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },

  // Additional work visa businesses for better coverage
  {
    id: "work-1",
    name: "Chennai Work Visa Experts",
    category: "Work Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Leading work visa consultancy in Chennai specializing in employment visas for USA, Canada, Europe, and Gulf countries.",
    services: [
      "H1B Visa Processing",
      "Work Permit Canada",
      "EU Work Visa",
      "Gulf Employment Visa",
    ],
    address: "Anna Salai, Chennai",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600002",
    phone: "+91-44-456-7890",
    email: "info@chennaworkvisaexperts.com",
    rating: 4.7,
    reviewCount: 189,
    isVerified: true,
    isFeatured: true,
    plan: "business",
    languages: ["Tamil", "English", "Hindi", "Telugu"],
    specializations: ["Work Visas", "Employment Immigration"],
    countriesServed: ["USA", "Canada", "UK", "Germany", "UAE", "Australia"],
    coordinates: { lat: 13.0827, lng: 80.2707 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },
  {
    id: "work-2",
    name: "Bangalore Employment Visa Services",
    category: "Work Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Trusted employment visa consultancy in Bangalore helping IT professionals secure work permits worldwide.",
    services: [
      "Tech Worker Visas",
      "Skilled Worker Immigration",
      "Corporate Transfers",
      "Work Permit Renewals",
    ],
    address: "Whitefield, Bangalore",
    city: "Bangalore",
    state: "Karnataka",
    pincode: "560066",
    phone: "+91-80-567-8901",
    email: "info@bangaloreemploymentvisa.com",
    rating: 4.5,
    reviewCount: 156,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["English", "Hindi", "Kannada", "Tamil"],
    specializations: ["IT Work Visas", "Tech Immigration"],
    countriesServed: [
      "USA",
      "Canada",
      "UK",
      "Australia",
      "Germany",
      "Netherlands",
    ],
    coordinates: { lat: 12.9716, lng: 77.5946 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },
  {
    id: "work-3",
    name: "Mumbai Global Work Solutions",
    category: "Work Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Premier work visa consultancy in Mumbai providing comprehensive employment immigration services.",
    services: [
      "Work Visa Processing",
      "Job Search Assistance",
      "Document Preparation",
      "Post-landing Support",
    ],
    address: "Andheri East, Mumbai",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400069",
    phone: "+91-22-678-9012",
    email: "info@mumbaiglobalwork.com",
    rating: 4.6,
    reviewCount: 234,
    isVerified: true,
    isFeatured: false,
    plan: "business",
    languages: ["Hindi", "English", "Marathi", "Gujarati"],
    specializations: ["Work Immigration", "Employment Services"],
    countriesServed: ["USA", "Canada", "UK", "Australia", "New Zealand", "UAE"],
    coordinates: { lat: 19.076, lng: 72.8777 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [],
  },

  // UAE businesses - Dubai
  {
    id: "11",
    name: "Emirates Visa Solutions",
    category: "Visa Consultant",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Leading visa consultancy in Dubai offering comprehensive immigration services for all emirates.",
    services: [
      "UAE Work Visa",
      "UAE Tourist Visa",
      "Family Visa",
      "Business Visa",
      "Golden Visa",
    ],
    address: "Business Bay, Dubai",
    city: "Dubai",
    state: "Dubai",
    pincode: "00000",
    phone: "+971-4-123-4567",
    email: "info@emiratesvisasolutions.ae",
    rating: 4.8,
    reviewCount: 245,
    isVerified: true,
    isFeatured: true,
    plan: "premium",
    languages: ["Arabic", "English", "Hindi", "Urdu"],
    specializations: ["UAE Visas", "Golden Visa", "Business Setup"],
    countriesServed: ["UAE", "USA", "UK", "Canada"],
    coordinates: { lat: 25.1972, lng: 55.2744 },
    paymentMethods: ["Cash", "Card", "Bank Transfer"],
    reviews: [],
  },
  {
    id: "12",
    name: "Dubai Immigration Center",
    category: "Immigration Lawyer",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Expert immigration lawyers in Dubai providing legal assistance for all UAE visa matters.",
    services: [
      "Legal Immigration Services",
      "Visa Appeals",
      "Citizenship Applications",
      "Work Permit Legal Help",
    ],
    address: "Al Barsha, Dubai",
    city: "Al Barsha",
    state: "Dubai",
    pincode: "00000",
    phone: "+971-4-234-5678",
    email: "info@dubaiimmigrationcenter.ae",
    rating: 4.7,
    reviewCount: 189,
    isVerified: true,
    isFeatured: false,
    plan: "basic",
    languages: ["Arabic", "English", "French"],
    specializations: ["Immigration Law", "Visa Appeals", "Legal Consultation"],
    countriesServed: ["UAE", "Europe", "USA"],
    coordinates: { lat: 25.1124, lng: 55.2039 },
    paymentMethods: ["Card", "Bank Transfer"],
    reviews: [],
  },
  {
    id: "13",
    name: "Al Barsha Visa Services",
    category: "Work Visa Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Specialized work visa consultants in Al Barsha helping professionals secure employment in UAE and abroad.",
    services: [
      "UAE Work Visa",
      "Employment Visa Processing",
      "Work Permit Assistance",
      "Job Placement Services",
    ],
    address: "Al Barsha 1, Dubai",
    city: "Al Barsha",
    state: "Dubai",
    pincode: "00000",
    phone: "+971-4-345-6789",
    email: "info@albarshavisa.ae",
    rating: 4.6,
    reviewCount: 156,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    languages: ["Arabic", "English", "Hindi", "Filipino"],
    specializations: [
      "Work Visas",
      "Employment Services",
      "Document Processing",
    ],
    countriesServed: ["UAE", "Canada", "Australia"],
    coordinates: { lat: 25.1138, lng: 55.2086 },
    paymentMethods: ["Cash", "Card", "Bank Transfer"],
    reviews: [],
  },

  // Abu Dhabi
  {
    id: "14",
    name: "Capital Immigration Services",
    category: "Immigration Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Premier immigration consultancy in Abu Dhabi with expertise in UAE and international visa services.",
    services: [
      "UAE Residence Visa",
      "Investment Visa",
      "Student Visa",
      "Family Reunion Visa",
    ],
    address: "Corniche Road, Abu Dhabi",
    city: "Abu Dhabi",
    state: "Abu Dhabi",
    pincode: "00000",
    phone: "+971-2-123-4567",
    email: "info@capitalimmigration.ae",
    rating: 4.9,
    reviewCount: 298,
    isVerified: true,
    isFeatured: true,
    plan: "premium",
    languages: ["Arabic", "English", "Hindi", "French"],
    specializations: [
      "Investment Visas",
      "Business Immigration",
      "Family Visas",
    ],
    countriesServed: ["UAE", "USA", "UK", "Canada", "Australia"],
    coordinates: { lat: 24.4539, lng: 54.3773 },
    paymentMethods: ["Cash", "Card", "Bank Transfer", "Cheque"],
    reviews: [],
  },

  // Sharjah
  {
    id: "15",
    name: "Sharjah Global Visa",
    category: "Study Abroad Consultant",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Leading study abroad consultants in Sharjah helping students achieve their international education dreams.",
    services: [
      "Student Visa Processing",
      "University Applications",
      "Scholarship Assistance",
      "Education Counseling",
    ],
    address: "Al Qasba, Sharjah",
    city: "Sharjah",
    state: "Sharjah",
    pincode: "00000",
    phone: "+971-6-123-4567",
    email: "info@sharjahglobalvisa.ae",
    rating: 4.5,
    reviewCount: 134,
    isVerified: true,
    isFeatured: false,
    plan: "basic",
    languages: ["Arabic", "English", "Hindi", "Urdu"],
    specializations: [
      "Student Visas",
      "Education Counseling",
      "University Admissions",
    ],
    countriesServed: ["USA", "UK", "Canada", "Australia", "Germany"],
    coordinates: { lat: 25.3548, lng: 55.4037 },
    paymentMethods: ["Cash", "Card", "Bank Transfer"],
    reviews: [],
  },

  // Education Consultants - Kolkata and nearby cities
  {
    id: "edu-1",
    name: "Kolkata Education Hub",
    category: "Education Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Premier education consultancy in Kolkata providing comprehensive academic guidance and career counseling services.",
    services: [
      "Academic Counseling",
      "Career Guidance",
      "University Admissions",
      "Scholarship Assistance",
      "Course Selection",
      "Educational Planning",
    ],
    address: "Park Street, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700016",
    phone: "+91-33-2234-5678",
    email: "info@kolkataeducationhub.com",
    rating: 4.6,
    reviewCount: 189,
    isVerified: true,
    isFeatured: true,
    plan: "premium",
    establishedYear: 2010,
    languages: ["Bengali", "English", "Hindi"],
    specializations: [
      "Higher Education",
      "Professional Courses",
      "Career Counseling",
    ],
    countriesServed: ["India"],
    coordinates: { lat: 22.5414, lng: 88.3513 },
    paymentMethods: ["Cash", "Card", "UPI", "Net Banking"],
    reviews: [
      {
        id: "edu-rev-1",
        userId: "user-edu-1",
        userName: "Priya Chatterjee",
        rating: 5,
        comment:
          "Excellent guidance for my engineering admissions. Very professional and knowledgeable staff.",
        isVerified: true,
        date: "2024-01-15",
      },
    ],
  },

  {
    id: "edu-2",
    name: "Bengal Education Consultants",
    category: "Education Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Trusted education advisory services in Kolkata specializing in professional course guidance and admission assistance.",
    services: [
      "Professional Course Guidance",
      "MBA Admissions",
      "Engineering Counseling",
      "Medical Entrance Coaching",
      "Competitive Exam Preparation",
    ],
    address: "Salt Lake Sector V, Kolkata",
    city: "Kolkata",
    state: "West Bengal",
    pincode: "700091",
    phone: "+91-33-4567-8901",
    email: "contact@bengaleducation.com",
    rating: 4.4,
    reviewCount: 156,
    isVerified: true,
    isFeatured: false,
    plan: "business",
    establishedYear: 2015,
    languages: ["Bengali", "English", "Hindi"],
    specializations: ["MBA", "Engineering", "Medical"],
    countriesServed: ["India"],
    coordinates: { lat: 22.5726, lng: 88.4639 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },

  {
    id: "edu-3",
    name: "Howrah Education Services",
    category: "Education Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Educational consultancy in Howrah providing comprehensive academic guidance and university admission support.",
    services: [
      "University Admissions",
      "Academic Planning",
      "Course Selection",
      "Educational Loans",
      "Career Counseling",
    ],
    address: "GT Road, Howrah",
    city: "Howrah",
    state: "West Bengal",
    pincode: "711101",
    phone: "+91-33-2678-9012",
    email: "info@howraheducation.com",
    rating: 4.3,
    reviewCount: 134,
    isVerified: true,
    isFeatured: false,
    plan: "premium",
    establishedYear: 2012,
    languages: ["Bengali", "English", "Hindi"],
    specializations: ["Higher Education", "Professional Courses"],
    countriesServed: ["India"],
    coordinates: { lat: 22.5958, lng: 88.2636 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },

  {
    id: "edu-4",
    name: "Durgapur Academic Consultants",
    category: "Education Consultants",
    logo: "/api/placeholder/80/80",
    coverImage: "/api/placeholder/800/400",
    description:
      "Leading education consultancy in Durgapur offering expert guidance for higher education and career development.",
    services: [
      "Higher Education Guidance",
      "Career Development",
      "University Applications",
      "Scholarship Information",
      "Academic Counseling",
    ],
    address: "City Centre, Durgapur",
    city: "Durgapur",
    state: "West Bengal",
    pincode: "713216",
    phone: "+91-343-234-5678",
    email: "contact@durgapuracademic.com",
    rating: 4.2,
    reviewCount: 98,
    isVerified: true,
    isFeatured: false,
    plan: "business",
    establishedYear: 2016,
    languages: ["Bengali", "English", "Hindi"],
    specializations: ["Engineering", "Technology", "Management"],
    countriesServed: ["India"],
    coordinates: { lat: 23.5204, lng: 87.3119 },
    paymentMethods: ["Cash", "Card", "UPI"],
    reviews: [],
  },
];

export const featuredBusinesses = sampleBusinesses.filter((b) => b.isFeatured);

// Listing Plans
export interface ListingPlan {
  id: string;
  name: string;
  price: number;
  period: string;
  description: string;
  features: string[];
  limitations?: string[];
  popular?: boolean;
  color: string;
  buttonColor: string;
}

export const listingPlans: ListingPlan[] = [
  {
    id: "free",
    name: "Free Listing",
    price: 0,
    period: "Forever",
    description: "Get started with basic listing features",
    features: [
      "Basic business profile",
      "Contact information display",
      "Business category listing",
      "Customer reviews",
      "Basic search visibility",
    ],
    limitations: [
      "Limited to 3 photos",
      "No priority ranking",
      "No featured badge",
      "Standard support only",
    ],
    color: "border-gray-200",
    buttonColor: "bg-gray-600 hover:bg-gray-700",
  },
  {
    id: "premium",
    name: "Premium",
    price: 2999,
    period: "per month",
    description: "Enhanced visibility and professional features",
    features: [
      "All Free features included",
      "Up to 20 photos & videos",
      "Premium badge & verification",
      "Priority search ranking",
      "Analytics dashboard",
      "WhatsApp integration",
      "Social media links",
      "Priority customer support",
    ],
    popular: true,
    color: "border-orange-300 bg-orange-50",
    buttonColor: "bg-orange-600 hover:bg-orange-700",
  },
  {
    id: "business",
    name: "Business Pro",
    price: 4999,
    period: "per month",
    description: "Complete business growth solution",
    features: [
      "All Premium features included",
      "Unlimited photos & videos",
      "Featured listing placement",
      "Homepage showcase opportunity",
      "Advanced analytics & insights",
      "Lead generation tools",
      "Multiple branch listings",
      "Dedicated account manager",
    ],
    color: "border-purple-300 bg-purple-50",
    buttonColor: "bg-purple-600 hover:bg-purple-700",
  },
];

export default sampleBusinesses;
